security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        main:
            oauth:
                resource_owners:
                    google: "/login"
                login_path:        fos_user_security_login
                use_forward:       false
                default_target_path: /

                oauth_user_provider:
                    service: app.fos_user.oauth_provider
            logout:
                path:   /logout
                target: /
            anonymous: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_FULLY }