<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxNZBqd\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxNZBqd/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxNZBqd.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxNZBqd\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerXxNZBqd\srcProdProjectContainer(array(
    'container.build_hash' => 'XxNZBqd',
    'container.build_id' => 'a265437b',
    'container.build_time' => 1523959552,
));
