index:
    path: /
    controller: App\Controller\HomeController::index

login:
  path: /login/
  controller: App\Controller\GoogleApiController::login

logout:
  path: /logout
  controller: App\Controller\GoogleApiController::logout

reminder:
  path: /remind
  controller: App\Controller\HomeController::reminder

kategorijos:
  path: /{kategorija}
  controller: App\Controller\HomeController::categories

delete:
  path: /delete/{id}
  controller: App\Controller\HomeController::delete

search:
  path: /search/{input}
  controller: App\Controller\HomeController::search
