index:
    path: /
    controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\GoogleApiController::login

logout:
  path: /logout
  controller: App\Controller\GoogleApiController::logout

reminder:
  path: /priminimai
  controller: App\Controller\HomeController::reminder

search:
  path: /search
  controller: App\Controller\searchController::index

kategorijos:
  path: /{kategorija}
  controller: App\Controller\HomeController::categories

delete:
  path: /delete/{id}
  controller: App\Controller\HomeController::delete


