<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJLpEZgb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJLpEZgb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJLpEZgb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJLpEZgb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJLpEZgb\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JLpEZgb',
    'container.build_id' => 'a1b157f6',
    'container.build_time' => 1524233000,
));
