<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZJxSlxx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZJxSlxx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZJxSlxx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZJxSlxx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZJxSlxx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZJxSlxx',
    'container.build_id' => '28ab672f',
    'container.build_time' => 1523959510,
));
